### ISSUE TITLE
Failed to Detect Introduction

### ISSUE THREAD

**Issue by TheBlueKingLP** [ConfusedPolarBear/intro-skipper#119]
### Describe the bug

Unable to detect introductions. When I click "Detect Introductions" in the scheduled tasks page, it just says "failed".

![image](https://user-images.githubusercontent.com/12997043/209849800-97532414-47ba-42d7-b49a-2903caeb7b0c.png)

### Operating system

Photon OS 4.0

### Jellyfin installation method

Docker

### Container image and tag

lscr.io/linuxserver/jellyfin:latest (Linuxserver.io version:- 10.8.8-1-ls193 Build-date:- 2022-12-14T20:50:03-06:00)

### Support Bundle

* Jellyfin version: 10.8.8
* Plugin version: 0.1.7
* Queue contents: 0 episodes, 0 seasons
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

### Jellyfin logs

```shell
[02:17:29] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing Detect Introductions
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Checking FFmpeg requirement -version
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Starting ffmpeg with the following arguments: -hide_banner -loglevel warning -version
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: FFmpeg requirement -version met
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Checking FFmpeg requirement -muxers
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Starting ffmpeg with the following arguments: -hide_banner -loglevel warning -muxers
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: FFmpeg requirement -muxers met
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Checking FFmpeg requirement -h muxer=chromaprint
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Starting ffmpeg with the following arguments: -hide_banner -loglevel warning -h muxer=chromaprint
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: FFmpeg requirement -h muxer=chromaprint met
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Checking FFmpeg requirement -h filter=silencedetect
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Starting ffmpeg with the following arguments: -hide_banner -loglevel info -h filter=silencedetect
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: FFmpeg requirement -h filter=silencedetect met
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Installed version of ffmpeg meets fingerprinting requirements
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Not limiting analysis by library name
[02:17:29] [INF] [13] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Analysis settings have been changed to: 50%/15m and a minimum of 15s
[02:17:29] [DBG] [13] Emby.Server.Implementations.Library.LibraryManager: Getting topLibraryFolders
[02:17:29] [DBG] [13] Emby.Server.Implementations.Library.LibraryManager: Getting refreshQueue
[02:17:29] [INF] [13] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Running enqueue of items in library TV Shows (null)
[02:17:29] [DBG] [13] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Constructing anonymous internal query
[02:17:29] [ERR] [13] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Failed to enqueue items from library TV Shows: System.ArgumentNullException: Value cannot be null. (Parameter 'input')
   at System.Guid.Parse(String input)
   at ConfusedPolarBear.Plugin.IntroSkipper.QueueManager.QueueLibraryContents(String rawId)
   at ConfusedPolarBear.Plugin.IntroSkipper.QueueManager.EnqueueAllEpisodes()
[02:17:29] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: Detect Introductions Failed after 0 minute(s) and 0 seconds
[02:17:29] [INF] [13] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```
```

**Comment by gaming09** [comment]
is your library Read Only? i noticed if its RO i get an error

**Comment by TheBlueKingLP** [comment]
Where do I check if the library is read only? If you mean the file system the library is in then no, jellyfin can write to it.

**Comment by gaming09** [comment]
> Where do I check if the library is read only? If you mean the file system the library is in then no, jellyfin can write to it.

Are you running docker ?is your media library lets say its  "tv" & "movies" read/write permissions on the mapping side?  

What platform are you running JF?

**Comment by TheBlueKingLP** [comment]
My library is mounted with write enabled. Platform information is stated in the original post. Thank you.

**Comment by Terror-Gene** [comment]
Ive just installed this plugin, it seemed to be working at first until i noticed it was only working on a test library, i deleted the test library & now i have an error basically the same as this.
Tried setting my mounted media folder to read/write but didnt make a difference.
Unfortunately at this stage this plugin does not work for me.
Seems very cool though, would love to help resolve the issue.

**Comment by lou-perret** [comment]
I had the same error, and It seems like triggering the library scan before fixed the problem. Can you try ?

**Comment by Terror-Gene** [comment]
Working now, but I did a few things after my post, so cant be sure as to the remedy. pretty sure i had scanned my library before i had the issue, but i did realize that my main TV Shows library had an additional old directory in it which didnt exist anymore, could have contributed to the issue. I ended up removing my library & creating a new one (library was made ages ago & i suspect it was harboring some outdated stuff, breaking things (i couldn't save after editing any library settings)).
after recreating the library & finishing a scan it seems that Intro-Skipper is now processing everything as expected.

**Comment by irnutsmurt** [comment]
> I had the same error, and it seems like triggering the library scan before fixed the problem. Can you try ?

Just wanted to say this fixed the issue for me. If the scanning of the library fails, then check the permissions.
