### ISSUE TITLE
"Erase introduction timestamps" button not working

### ISSUE THREAD

**Issue by memehammad** [ConfusedPolarBear/intro-skipper#123]
### Describe the bug

Hey, ive changed some settings so i wanted to redo the analysation. However clicking the erase introduction timestamps button doesnt seem to do anything since once I start the detect introductions task it just goes to 100% within like 3 seconds without doing anything. So far I've tried reinstalling the plugin and rebooting. 
Is there a way to manually delete the timestamps?

### Operating system

Unraid

### Jellyfin installation method

Docker

### Container image and tag

linuxserver/jellyfin

### Support Bundle

* Jellyfin version: 10.8.8
* Plugin version: 0.1.7
* Queue contents: 1339 episodes, 116 seasons
* FFmpeg: `okay`

FFmpeg version:
```
ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

### Jellyfin logs
```
[2023-01-06 17:21:10.126 +01:00] [WRN] [28] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv""
[2023-01-06 17:21:10.127 +01:00] [WRN] [28] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.AnalyzeSeason(ReadOnlyCollection`1 episodes, CancellationToken cancellationToken)"
[2023-01-06 17:23:08.383 +01:00] [WRN] [31] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E04 - Aperitivo.mkv""
[2023-01-06 17:23:08.384 +01:00] [WRN] [31] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E04 - Aperitivo.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.AnalyzeSeason(ReadOnlyCollection`1 episodes, CancellationToken cancellationToken)"
[2023-01-06 17:23:08.581 +01:00] [WRN] [31] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv""
[2023-01-06 17:23:08.581 +01:00] [WRN] [31] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.AnalyzeSeason(ReadOnlyCollection`1 episodes, CancellationToken cancellationToken)"
[2023-01-06 17:25:50.132 +01:00] [WRN] [33] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E04 - Aperitivo.mkv""
[2023-01-06 17:25:50.133 +01:00] [WRN] [33] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E04 - Aperitivo.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.AnalyzeSeason(ReadOnlyCollection`1 episodes, CancellationToken cancellationToken)"
[2023-01-06 17:25:50.354 +01:00] [WRN] [33] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv""
[2023-01-06 17:25:50.354 +01:00] [WRN] [33] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.AnalyzeSeason(ReadOnlyCollection`1 episodes, CancellationToken cancellationToken)"
[2023-01-06 17:32:12.098 +01:00] [WRN] [11] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E04 - Aperitivo.mkv""
[2023-01-06 17:32:12.098 +01:00] [WRN] [11] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E04 - Aperitivo.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.FFmpegWrapper.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.AnalyzeSeason(ReadOnlyCollection`1 episodes, CancellationToken cancellationToken)"
[2023-01-06 17:32:12.290 +01:00] [WRN] [11] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Chromaprint returned 0 points for ""/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv""
[2023-01-06 17:32:12.291 +01:00] [WRN] [11] ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/data/tvshows/Serien/Hannibal/Season 3/Hannibal - S03E05 - Contorno.mkv\" was malformed
```

**Comment by memehammad** [comment]
Update: Deleting the "ConfusedPolarBear.Plugin.IntroSkipper.xml" and "Intros" folder in jellyfin/data/plugins/configurations fixed this issue.
