### ISSUE TITLE
Could not open the input file

### ISSUE THREAD

**Issue by LubricantJam** [ConfusedPolarBear/intro-skipper#16]
Hey,

We are trying to run a scan and getting constant errors like ![Image](https://images-ext-1.discordapp.net/external/w0lqQFvQepneVGZFFSLA1SOAok6H80uji7egnWheKtQ/https/i.imgur.com/7O69xFD.png)

Is there any way to see what this actually is and have you seen this before?

**Comment by ConfusedPolarBear** [comment]
I have not seen this error before. You'll have to install a nightly version of the plugin from [GitHub Actions](https://github.com/ConfusedPolarBear/intro-skipper/suites/6886587927/artifacts/266748089) in order to see which path(s) can't be accessed.

**Comment by cooljimy84** [comment]
using the 
'''intro-skipper-a29f2a94bb9117747875dc47318b4c4ca4e66d2b.dll'''
and enabling debug in the config i have a few examples (at least from my system)

```
[2022-06-13 10:43:01.268 +01:00] [DBG] Fingerprinting 309 seconds from "/mnt/TV Shows/Cosmic Kids Yoga/Season 1/Cosmic Kids Yoga - S01E23 - Stella the Stick Insect.webm"
[2022-06-13 10:43:01.293 +01:00] [ERR] Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for /mnt/TV Shows/Cosmic Kids Yoga/Season 1/Cosmic Kids Yoga - S01E23 - Stella the Stick Insect.webm was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
```


```
[2022-06-13 10:43:01.405 +01:00] [DBG] Fingerprinting 0 seconds from "/mnt/TV Shows/Marvel Disk Wars- The Avengers/Season 1/Marvel Disk Wars- The Avengers - S01E17 - That Man, Wolverine!.mp4"
[2022-06-13 10:43:01.425 +01:00] [DBG] Fingerprint cache hit on "/mnt/TV Shows/Cosmic Kids Yoga/Season 1/Cosmic Kids Yoga - S01E30 - Kids Yoga Christmas Special!.webm"
[2022-06-13 10:43:01.425 +01:00] [DBG] Fingerprint cache hit on "/mnt/TV Shows/Cosmic Kids Yoga/Season 1/Cosmic Kids Yoga - S01E31 - Betsy the Banana.webm"
[2022-06-13 10:43:01.435 +01:00] [ERR] Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for /mnt/TV Shows/Marvel Disk Wars- The Avengers/Season 1/Marvel Disk Wars- The Avengers - S01E17 - That Man, Wolverine!.mp4 was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"

```

Both files 'seem' to play fine (tho i've not watched all the way through to check)

**Comment by VampiricAlien** [comment]
@ConfusedPolarBear I see this in the logs heaps of times.
