### ISSUE TITLE
Server not working after plugin install

### ISSUE THREAD

**Issue by ShiniGandhi** [ConfusedPolarBear/intro-skipper#17]
I'm trying to install the plugin and it doesn't seem to work at all. After replacing my container Image everything loads up fine, but once I install the plugin and restart I [get this](https://pastebin.com/GBgvnUUM).
I'm trying to install version v0.1.0 (v0.0.3 also didn't work), and I changed from the `linuxserver/jellyfin` image (10.8.0) if it matters (I remapped the directories as [this comment explains](https://github.com/jellyfin/jellyfin/issues/3717#issuecomment-665966147), and everything kept working as usual.

Am I doing something wrong?

UPDATE: seems like installing the plugin with my original image lets the server load, but it doesn't scan. I've tried installing `fpcalc` (using `libchromaprint-tools`) and it makes Jellyfin crash with the same error, so I'm guessing that's the issue.

**Comment by Fallenbagel** [comment]
> UPDATE: seems like installing the plugin with my original image lets the server load, but it doesn't scan. I've tried installing `fpcalc` (using `libchromaprint-tools`) and it makes Jellyfin crashe with the same error, so I'm guessing that's the issue.

That's odd. I'm running official jellyfin image with fpcalc installed and it works perfectly for me with no crashes

**Comment by ConfusedPolarBear** [comment]
Using an official & unmodified Jellyfin 10.8.0 stable container, can you:
1. [Enable debug logging](https://github.com/ConfusedPolarBear/intro-skipper/blob/master/docs/debug_logs.md) for the plugin
2. Install this [unstable build](https://github.com/ConfusedPolarBear/intro-skipper/suites/6900155609/artifacts/267764747) of the plugin
3. Post the logs of the container starting

**Comment by ShiniGandhi** [comment]
[Seems like it thinks chromaprint is not installed. Isn't it supposed to be installed by default on 10.8.0?](https://pastebin.com/raw/Pdvz4Nms)

**Comment by LubricantJam** [comment]
> [Seems like it thinks chromaprint is not installed. Isn't it supposed to be installed by default on 10.8.0?](https://pastebin.com/raw/Pdvz4Nms)

The plugin has not yet been updated to support this, you still need to install it for now.

**Comment by Fallenbagel** [comment]
> [Seems like it thinks chromaprint is not installed. Isn't it supposed to be installed by default on 10.8.0?](https://pastebin.com/raw/Pdvz4Nms)

The linuxserver image has not updated their ffmpeg version. From your logs it says `ffmpeg v4.4.1`. The libchromaprint was enabled by default in jellyfin-ffmpeg [5.0.1-5](https://github.com/jellyfin/jellyfin-ffmpeg/releases/tag/v5.0.1-5)

**Comment by ShiniGandhi** [comment]
[This is my log with the official Jellyfin image. looks like it has `jellyfin-ffmpeg 5.0.1`](https://pastebin.com/raw/zYu268SE). Still nothing unfortunately. Is it possible I haven't set up the libraries I want it to process? I haven't seen anywhere to config it.

**Comment by ShiniGandhi** [comment]
Another update: Looked at the logs again, looks like it does work with the official image as I mentioned, and this is the error message: `[ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: Unable to run startup enqueue: System.NullReferenceException: Object reference not set to an instance of an object.`. I get the same thing on both 1.0 and 1.5 versions of the plugin.

**Comment by ConfusedPolarBear** [comment]
> Is it possible I haven't set up the libraries I want it to process?

There's currently no way to specify the libraries that are processed - the plugin just queues all episodes from all libraries for analysis. I might include that feature in a later version of the plugin though (tracked by #5).

I rewrote the startup item queuing code - can you try [this build](https://github.com/ConfusedPolarBear/intro-skipper/suites/6937069694/artifacts/270122978) on an official 10.8.0 container?

**Comment by ShiniGandhi** [comment]
> I rewrote the startup item queuing code - can you try [this build](https://github.com/ConfusedPolarBear/intro-skipper/suites/6937069694/artifacts/270122978) on an official 10.8.0 container?

It "say" that it's scanning, but all I get in the logs is:
```[2022-06-15 11:17:41.763 +03:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Update Plugins" Completed after 0 minute(s) and 4 seconds
[2022-06-15 11:17:41.767 +03:00] [INF] [14] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-06-15 11:17:54.069 +03:00] [INF] [30] Emby.Server.Implementations.IO.LibraryMonitor: Watching directory "/data/movies"
[2022-06-15 11:17:57.540 +03:00] [INF] [28] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Analyze episodes"
[2022-06-15 11:17:57.561 +03:00] [INF] [35] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Analyzing 20 episodes from "פני הרוע" season 1
[2022-06-15 11:17:57.562 +03:00] [INF] [28] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Analyzing 8 episodes from "פריצ'ר" season 1
[2022-06-15 11:17:57.589 +03:00] [ERR] [28] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.590 +03:00] [ERR] [35] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.643 +03:00] [ERR] [35] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.650 +03:00] [ERR] [28] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.664 +03:00] [ERR] [35] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.672 +03:00] [ERR] [28] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.734 +03:00] [ERR] [28] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
[2022-06-15 11:17:57.735 +03:00] [ERR] [35] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for  was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
```

Also, I'm not sure if it's relevant, but `docker-compose logs -f` gives me this:
```jellyfin    | [NULL @ 0x564ed7ce6840] missing picture in access unit with size 38834
jellyfin    | [NULL @ 0x564ed7ce6840] Invalid NAL unit size (1865739102 > 24117).
jellyfin    | [NULL @ 0x564ed7ce6840] missing picture in access unit with size 24121
jellyfin    | [NULL @ 0x564ed7ce6840] Invalid NAL unit size (-1162508120 > 32163).
jellyfin    | [NULL @ 0x564ed7ce6840] missing picture in access unit with size 32167
```

**Comment by ConfusedPolarBear** [comment]
Looks like some episodes either didn't have a path provided by Jellyfin or it wasn't passed to ffmpeg properly. The attached build (built from commit 4d2181a2) ignores episodes without a path and will also log more of ffmpeg's output. Could you test it after enabling debug logging?

[ConfusedPolarBear.Plugin.IntroSkipper.zip](https://github.com/ConfusedPolarBear/intro-skipper/files/8931723/ConfusedPolarBear.Plugin.IntroSkipper.zip)

**Comment by ShiniGandhi** [comment]
After replacing the `dll` file, looks like Jellyfin also autoupdated the plugin to 1.5, so it disregarded the build you've sent, but looks like it's analyzing now and skipping intros work. Do you still want me to test the build you attached?

**Comment by ConfusedPolarBear** [comment]
> Do you still want me to test the build you attached?

Since 1.5 fixed your issues, there's no need to test that build. Glad to hear that it works now.
