### ISSUE TITLE
[Bug] Error processing request. URL "GET" "/Intros/Shows".

### ISSUE THREAD

**Issue by sourpatched** [ConfusedPolarBear/intro-skipper#27]
**Describe the bug**

**System information**
- Plugin version: latest
- Jellyfin version: 10.8.0
- Jellyfin installation method: Deb file
- OS: ubuntu 20.04

**Jellyfin logs**
[2022-06-19 15:32:16.777 +10:00] [ERR] Error processing request. URL "GET" "/Intros/Shows".
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at ConfusedPolarBear.Plugin.IntroSkipper.Controllers.VisualizationController.GetShowSeasons()
   at lambda_method1083(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
[2022-06-19 15:33:19.240 +10:00] [INF] Executing "Analyze episodes"

After a new minutes dashboard [Running tasks] starting to count from 0.01% but not sure if it's working as I can't find any new files and nothing else shows in the logs.

Are we able to have a log file for this that shows every what is going on and more info on how this plugin works for those who have limited IT knowledge? I understand how it works but not where the files are stored? I was thinking inside the shows folder?

**Comment by sourpatched** [comment]
After 5 seconds it auto skipped on the web client.

**Comment by VossenTech** [comment]
I am seeing this same error on a fresh docker install
Intro Skipper 0.1.5.0
Jellyfin 10.8.0
Linuxserver.io docker image on ubuntu 20.04 host

With Cache fingerprints to disk disabled I get the same error as OP, when enabled it still fails but provides a different error:

ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Unable to analyze "redacted" season 5: cache miss: "System.Collections.Generic.KeyNotFoundException: The given key '8f22f85b-6830-6609-d07b-88f80b50a728' was not present in the dictionary.
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.RunSecondPass(List`1 episodes)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.<>c__DisplayClass19_0.<ExecuteAsync>b__0(KeyValuePair`2 season)"

Not sure if that is related or a separate issue, but figured it was worth mentioning.

**Comment by ConfusedPolarBear** [comment]
> Error processing request. URL "GET" "/Intros/Shows".
> System.ArgumentNullException: Value cannot be null. (Parameter 'key')
> at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
> at ConfusedPolarBear.Plugin.IntroSkipper.Controllers.VisualizationController.GetShowSeasons()

Fixed by c72d8ba.

> Are we able to have a log file for this that shows every what is going on and more info on how this plugin works for those who have limited IT knowledge?

The next version of the plugin (v0.1.6 [[beta version](https://github.com/ConfusedPolarBear/intro-skipper/releases/tag/v0.1.6-beta2)]) will log the name of each show and season number as the plugin is starting to analyze it.

> I understand how it works but not where the files are stored?

After a season is analyzed, the timestamps of all introductions are serialized as XML to `CONFIG_DIR/plugins/configurations/intros/intros.xml`

---

> ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Unable to analyze "redacted" season 5: cache miss: "System.Collections.Generic.KeyNotFoundException: The given key '8f22f85b-6830-6609-d07b-88f80b50a728' was not present in the dictionary.

This should also be fixed in v0.1.6.
