### ISSUE TITLE
Input string was not in a correct format.

### ISSUE THREAD

**Issue by alexh-name** [ConfusedPolarBear/intro-skipper#28]
**Describe the bug**
Sporadically after a while of analysing error "Input string was not in a correct format." occurs and analysing stops. Upon triggering the analysing again, the error occurs almost immediately, after a bunch of "ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Analyzing XX episodes from XX season XX".

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: jellyfin-intro-skipper:latest docker image
- OS: linux/amd64

**Jellyfin logs**
```
[...]
[DBG] [77] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Analyzing 10 episodes from Squid Game season 1
[DBG] [77] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Analyzing 26 episodes from King of the Hill season 3
[ERR] [77] System.AggregateException: One or more errors occurred. (Input string was not in a correct format.)
  ---> System.FormatException: Input string was not in a correct format.
    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
    at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.LoadCachedFingerprint(QueuedEpisode episode, ReadOnlyCollection`1& fingerprint)
    at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
    at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
    at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)
    at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.<>c__DisplayClass19_0.<ExecuteAsync>b__0(KeyValuePair`2 season)
    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
 --- End of stack trace from previous location ---
    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
 --- End of stack trace from previous location ---
    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
    at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
    at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

**Comment by alexh-name** [comment]
I also noticed now that the only consistent debug log close to the error is
`Fingerprint cache hit on ONE_SPECIFIC_EPISODE`.

**Comment by ConfusedPolarBear** [comment]
Does [this build](https://github.com/ConfusedPolarBear/intro-skipper/suites/7001540841/artifacts/274617076) analyze the season correctly?

**Comment by alexh-name** [comment]
Now it just quits immediately quietly: `Analyze episodes Completed after 0 minute(s) and 0 seconds`
I am not sure I applied the new build correctly. I replaced the dll in the plugin folder, restarted Jellyfin with "Update plugins on startup" disabled, because otherwise it would just fetch 0.1.5.0 again.

**Comment by alexh-name** [comment]
doesn’t occur anymore in v0.1.6
