### ISSUE TITLE
[Bug] Cant make plugin to work

### ISSUE THREAD

**Issue by khoint0210** [ConfusedPolarBear/intro-skipper#29]
**Describe the bug**
Run plugin and it return failed

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 1.8.0
- Jellyfin installation method: native service
- OS: Ubuntu 20.04

**Jellyfin logs**
```
[2022-06-19 22:41:27.929 +07:00] [INF] ExecuteQueuedTasks
[2022-06-19 22:41:28.934 +07:00] [INF] Executing "Analyze episodes"
[2022-06-19 22:41:28.936 +07:00] [ERR] Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze: either no show libraries are defined or ffmpeg could not be found
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-06-19 22:41:28.937 +07:00] [INF] "Analyze episodes" Failed after 0 minute(s) and 0 seconds
[2022-06-19 22:41:28.939 +07:00] [INF] ExecuteQueuedTasks
[2022-06-19 22:41:29.400 +07:00] [INF] Executing "Analyze episodes"
[2022-06-19 22:41:29.401 +07:00] [ERR] Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze: either no show libraries are defined or ffmpeg could not be found
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-06-19 22:41:29.402 +07:00] [INF] "Analyze episodes" Failed after 0 minute(s) and 0 seconds
[2022-06-19 22:41:29.403 +07:00] [INF] ExecuteQueuedTasks
[2022-06-19 22:41:29.579 +07:00] [INF] Executing "Analyze episodes"
[2022-06-19 22:41:29.581 +07:00] [ERR] Error
```
<img width="1227" alt="CleanShot 2022-06-19 at 22 52 44@2x" src="https://user-images.githubusercontent.com/12799726/174489672-7bd2d347-c4c2-450b-ac35-5a4b1acabadf.png">

**Comment by sourpatched** [comment]
`No episodes to analyse: either no show libraries are defined`
What FFmpeg are you using?
Is your library set for TV Shows?

**Comment by sourpatched** [comment]
> FFmpeg currently using the one jellyfin provide I switch back to older version which is 0.1.0.0 it worked not sure why

I am using 1.5.0 and working for me and we're having the same server setup.

Jellyfin 10.8.0?
Jellyfin FFmpeg 5.0.1?
