### ISSUE TITLE
[Bug] either no show libraries are defined or ffmpeg could not be found (linuxserver)

### ISSUE THREAD

**Issue by EVOTk** [ConfusedPolarBear/intro-skipper#32]
**Describe the bug**
The scanner does not launch.
The problem comes I think from the fact that I use the linuxserver image, but I do not know how to solve it
Thx

**System information**
- Plugin version: [v0.1.5.0](https://github.com/ConfusedPolarBear/intro-skipper/releases/tag/v0.1.5.0)
- Jellyfin version: 10.8.0
- Jellyfin installation method: Docker ( [Linuxserver ](https://github.com/linuxserver/docker-jellyfin))
- OS: OMV 6

**Jellyfin logs**
```
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze: either no show libraries are defined or ffmpeg could not be found
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
```

Log similar to https://github.com/ConfusedPolarBear/intro-skipper/issues/29

**Comment by sourpatched** [comment]
FFmpeg Version 5?
