### ISSUE TITLE
[Bug] analyze episodes task fails to run

### ISSUE THREAD

**Issue by altered-beast** [ConfusedPolarBear/intro-skipper#35]
**Describe the bug**
the Analyze episodes task fails to run (error in logs below)

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: native through apt repo
- OS: Debian

**Jellyfin logs**
```
[2022-06-22 15:00:01.120 +00:00] [INF] Executing "Analyze episodes"
[2022-06-22 15:00:01.121 +00:00] [ERR] Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze: either no show libraries are defined or ffmpeg could not be found
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress 1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-06-22 15:00:01.121 +00:00] [INF] "Analyze episodes" Failed after 0 minute(s) and 0 seconds
[2022-06-22 15:00:01.123 +00:00] [INF] ExecuteQueuedTasks
```

**Comment by altered-beast** [comment]
i tried installing ffmpeg separately and verified it supported` -fp_format raw` and was built with `--enable-chromaprint` but there was no change

**Comment by altered-beast** [comment]
ok turns out my jellyfin ffmpeg version was out of date so i installed jellyfin-ffmpeg5 and that seems to have fixed it
