### ISSUE TITLE
[Bug] log file does not specify jellyfin-ffmpeg5 needed for native install

### ISSUE THREAD

**Issue by thyme676** [ConfusedPolarBear/intro-skipper#45]
**Describe the bug**
Task to analyze shows fails.

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.0
- Jellyfin installation method: Via Repo
- OS: Ubuntu 22.04 LTS (GNU/Linux 5.15.0-40-generic x86_64)

**Jellyfin logs**
```
[2022-06-26 14:07:52.520 -07:00] [INF] ExecuteQueuedTasks
[2022-06-26 14:07:52.678 -07:00] [INF] Executing "Analyze episodes"
[2022-06-26 14:07:52.678 -07:00] [ERR] Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze: either no show libraries are defined or ffmpeg could not be found
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-06-26 14:07:52.678 -07:00] [INF] "Analyze episodes" Failed after 0 minute(s) and 0 seconds
```

**Comment by thyme676** [comment]
I figured this out, I have a native install and needed jellyfin-ffmpeg5 to be installed. It would be helpful if this was listed in the log line.
