### ISSUE TITLE
[Bug] No show libraries are defined or ffmpeg could not be found

### ISSUE THREAD

**Issue by Weevild** [ConfusedPolarBear/intro-skipper#59]
**Describe the bug**
After following the installation guide and running the scheduled task I receive an instant "failed" prompt. Digging into the logs it states that the issue has probably arose from the lack of a defined media path or no ffmpeg present. Ffmpeg is present and should be up-to-date according to you (_Plugin versions v0.1.5 and newer require jellyfin-ffmpeg >= 5.0.1-5 to be installed. This is installed by default in the official Jellyfin 10.8.0 container_). I don't know of a way to check the version so please guide me on that if it's needed. The library part I don't know how to solve (if that is the root cause of this issue), so help with that would also be greatly appreciated.

**System information**
- Plugin version: 0.1.5.0
- Jellyfin version: 10.8.1
- Jellyfin installation method: Docker (via Unraid)
- OS: Unraid 

**Jellyfin logs**
```
2022-07-24 21:04:40,020 DEBG 'jellyfin' stdout output:
[21:04:40] [ERR] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze: either no show libraries are defined or ffmpeg could not be found
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options) in /tmp/makepkg/jellyfin/src/jellyfin-10.8.1/Emby.Server.Implementations/ScheduledTasks/ScheduledTaskWorker.cs:line 417

2022-07-24 21:04:40,021 DEBG 'jellyfin' stdout output:
[21:04:40] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: Analyze episodes Failed after 0 minute(s) and 0 seconds

2022-07-24 21:04:40,023 DEBG 'jellyfin' stdout output:
[21:04:40] [INF] [8] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

**Comment by Weevild** [comment]
Looks like I'm suffering from the same issue as [this issue](https://github.com/ConfusedPolarBear/intro-skipper/issues/52).
