### ISSUE TITLE
v0.1.6 Malfunctioned after upgrade

### ISSUE THREAD

**Issue by ShakeSp33r** [ConfusedPolarBear/intro-skipper#69]
**Describe the bug**
v0.16 Malfunctioned after upgrade. I uninstalled Intro Skipper again, deleted all Intro Skipper directories in the Plugin directory and did a clean installation, same thing.
I've noticed in the log _There is an error in XML document (244434, 2)_

**System information**
- Plugin version: 0.1.6.0
- Jellyfin version: 10.8.3
- Jellyfin installation method: linuxserver/jellyfin Docker
- OS: 

**Jellyfin logs**
```
[2022-08-05 09:18:00.987 +02:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Error creating "ConfusedPolarBear.Plugin.IntroSkipper.Plugin"
System.InvalidOperationException: There is an error in XML document (244434, 2).
 ---> System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Intro, ArrayOfIntro. Line 244434, position 2.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read2_Intro(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderList1.Read3_ArrayOfIntro()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromStream(Type type, Stream stream)
   at Emby.Server.Implementations.Serialization.MyXmlSerializer.DeserializeFromFile(Type type, String file)
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin.RestoreTimestamps()
   at ConfusedPolarBear.Plugin.IntroSkipper.Plugin..ctor(IApplicationPaths applicationPaths, IXmlSerializer xmlSerializer, IServerConfigurationManager serverConfiguration, ILibraryManager libraryManager)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Emby.Server.Implementations.Plugins.PluginManager.CreatePluginInstance(Type type)
```

**Comment by ShakeSp33r** [comment]
After deleting the intros directory also, Intro Skipper started successfully.
