### ISSUE TITLE
[Bug] Chromaprint output was malformed

### ISSUE THREAD

**Issue by Alexander-LIT** [ConfusedPolarBear/intro-skipper#73]
**Describe the bug**
Thank you for an awesome plugin! 
Not sure if this is a bug, current limitation or configuration issue.
The plugin works quite well on some of my shows, however on a lot of them no skipping is possible, and I am seeing fingerprint errors "chromaprint output was malformed" in the logs.
Is there anything I could be doing to remedy this?

Cheers!

**System information**
- Plugin version: v0.1.6
- Jellyfin version: 10.8.3
- Jellyfin installation method: native
- OS: Manjaro 21.3.6

**Jellyfin logs**
```
[2022-08-14 11:24:56.450 +02:00] [ERR] [30] ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask: Caught fingerprint error: "ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: chromaprint output for \"/mnt/media/series/My Show/My Show S03/My.Show.S03E01.The.Title.BluRay.10Bit.1080p.DD5.1.H265-d3g.mkv\" was malformed
   at ConfusedPolarBear.Plugin.IntroSkipper.Chromaprint.Fingerprint(QueuedEpisode episode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.FingerprintEpisodes(QueuedEpisode lhsEpisode, QueuedEpisode rhsEpisode)
   at ConfusedPolarBear.Plugin.IntroSkipper.FingerprinterTask.AnalyzeSeason(KeyValuePair`2 season, CancellationToken cancellationToken)"
```

**Comment by mueslimak3r** [comment]
Perhaps the input to ffmpeg was the wrong same rate? the docs say it needs to be 16 bit (https://ffmpeg.org/ffmpeg-all.html#toc-chromaprint-1)

Maybe normalizing the input to a certain bit-depth, sample-rate, and channel number would be good. Example (not tested) using 16 bit 48Khz mono:
`ffmpeg -i \"{0}\" -to {1} -acodec  pcm_s16le -ar 48000 -ac 1 -f chromaprint -fp_format raw -`

**Comment by Mavyre** [comment]
It seems to do that on EAC3 with Atmos (JOC) on my end. I have no other issue than a single show. Everything else is AAC/AC3 and "classic" EAC3

**Comment by Pingger** [comment]
"Opus" doesn't work either

**Comment by semliki** [comment]
Will there ever be any update to this (or [this](https://github.com/ConfusedPolarBear/intro-skipper/issues/16)) bug, or is it just going to be forgotten by the dev? Can't fully process my library due to one single file stopping the process. It's quite annoying. Hopefully when I get new hardware it won't be as much of an issue since I can actually transcode, but it's still probably going to affect me (and other people) regardless. 

I'm thinking about mucking around with the code and trying to fix it myself but I dont know how to build these addons, or test them.
