### ISSUE TITLE
[Bug] Detect Introduction fails to execute

### ISSUE THREAD

**Issue by sumin-cho** [ConfusedPolarBear/intro-skipper#96]
**Describe the bug**

Scheduled Tasks > Intro Skipper > Detect Introduction fails to execute, whether library is specified or not.

**System information**

- Jellyfin installation method: Server from installer
- OS: Windows

**Support bundle**

[go to Dashboard -> Plugins -> Intro Skipper -> Support Bundle (at the bottom of the page) and paste the contents of the textbox here]

```
* Jellyfin version: 10.8.5
* Plugin version: 0.1.7
* Queue contents: 0 episodes, 0 seasons
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10-win32 (GCC) 20220324
configuration: --prefix=/opt/ffmpeg --arch=x86_64 --target-os=mingw32 --cross-prefix=x86_64-w64-mingw32- --pkg-config=pkg-config --pkg-config-flags=--static --extra-libs='-lfftw3f -lstdc++' --extra-cflags=-DCHROMAPRINT_NODLL --extra-version=Jellyfin --disable-ffplay --disable-debug --disable-doc --disable-sdl2 --disable-ptx-compression --disable-w32threads --enable-pthreads --enable-shared --enable-lto --enable-gpl --enable-version3 --enable-schannel --enable-iconv --enable-libxml2 --enable-zlib --enable-lzma --enable-gmp --enable-chromaprint --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libass --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libwebp --enable-libvpx --enable-libzimg --enable-libx264 --enable-libx265 --enable-libsvtav1 --enable-libdav1d --enable-libfdk-aac --enable-opencl --enable-dxva2 --enable-d3d11va --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100

```

**Jellyfin logs**

```
[2022-10-29 01:43:33.795 +08:00] [INF] [46] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
[2022-10-29 01:43:34.589 +08:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Detect Introductions"
[2022-10-29 01:43:34.673 +08:00] [INF] [45] ConfusedPolarBear.Plugin.IntroSkipper.QueueManager: Analysis settings have been changed to: 50%/15m and a minimum of 8s
[2022-10-29 01:43:34.674 +08:00] [ERR] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: No episodes to analyze. If you are limiting the list of libraries to analyze, check that all library names have been spelled correctly.
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-10-29 01:43:34.675 +08:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Introductions" Failed after 0 minute(s) and 0 seconds
[2022-10-29 01:43:34.677 +08:00] [INF] [45] Emby.Server.Implementations.ScheduledTasks.TaskManager: ExecuteQueuedTasks
```

**Comment by aleksasiriski** [comment]
+1

**Comment by aleksasiriski** [comment]
Using jellyfin-intro-skipper docker image, which is using jellyfin official image:

```
[2022-10-29 21:09:05.654 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Detect Introductions"
[2022-10-29 21:09:05.835 +02:00] [ERR] [58] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: "The installed version of ffmpeg does not support chromaprint"
[2022-10-29 21:09:05.835 +02:00] [ERR] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: ffmpeg with chromaprint is not installed on this system - episodes will not be analyzed. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade it to the latest version of 10.8.0.
   at ConfusedPolarBear.Plugin.IntroSkipper.QueueManager.EnqueueAllEpisodes()
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-10-29 21:09:05.835 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Introductions" Failed after 0 minute(s) and 0 seconds
```

* Jellyfin version: 10.8.5
* Plugin version: 0.1.7
* Queue contents: 0 episodes, 0 seasons
* FFmpeg: `chromaprint_not_supported`

FFmpeg version:
```
ffmpeg version 5.1.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

FFmpeg muxer list:
```
```

**Comment by ganonleboucher** [comment]
Same here (on Debian and in Docker)
**Support bundle**
```
* Jellyfin version: 10.8.6
* Plugin version: 0.1.7
* Queue contents: 0 episodes, 0 seasons
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 5.1.2-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libsvtav1 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

**Comment by ConfusedPolarBear** [comment]
1. Are your TV shows stored in a mixed library?

**Comment by sumin-cho** [comment]
There are TV shows and movies in the same folder. Is this what you mean?

**Comment by ganonleboucher** [comment]
On hard drive the files are organize like this:
HDD
   |---->Video
                |---->Movie
                |---->Japanime
                |---->Tv Show
                              |---->Tv Show 1
                              |              |---->Season 01
                              |              |               |---->Ep 01
                              |              |               |---->Ep 02
                              |              |               |---->And so on
                              |              |---->Season 02
                              |              |               |---->Ep 01
                              |              |               |---->And so on
                              |              |---->Season XX
                              |---->Tv Show YY
                              |              |---->Season XX
                              |              |               |---->Ep ZZ

On Jellyfin i have few librairies : 
 - Movies which is movies type
 - Japanime and Tv Show which is mixed type respectively (if i remember well because i made them a while ago, but in my librairies dashboard it's say "Other")
Hope it help!

**Comment by ConfusedPolarBear** [comment]
> There are TV shows and movies in the same folder. Is this what you mean?

Yes. The current version of the plugin (v0.1.7) does not analyze mixed libraries (i.e. libraries with a type of `Other` listed in the dashboard). Support for mixed libraries has been added in bcb5e5ea300c9e4a3efe3c9517d937ab6667e065 and will be released in the next version.
