### ISSUE TITLE
[Bug] Detect Introduction fails to execute

### ISSUE THREAD

**Issue by aleksasiriski** [ConfusedPolarBear/intro-skipper#98]
**Describe the bug**

chromaprint not supported in your image

**System information**

- Jellyfin installation method: docker, jellyfin-intro-skipper image
- OS: Rocky Linux 9 on Hetzner VPS

**Support bundle**

[go to Dashboard -> Plugins -> Intro Skipper -> Support Bundle (at the bottom of the page) and paste the contents of the textbox here]

* Jellyfin version: 10.8.5
* Plugin version: 0.1.7
* Queue contents: 0 episodes, 0 seasons
* FFmpeg: `chromaprint_not_supported`

FFmpeg version:
```
ffmpeg version 5.1.1-Jellyfin Copyright (c) 2000-2022 the FFmpeg developers
built with gcc 10 (Debian 10.2.1-6)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-libs=-lfftw3f --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-shared --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-static --enable-gmp --enable-gnutls --enable-chromaprint --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libdav1d --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-opencl --enable-vaapi --enable-amf --enable-libmfx --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      57. 28.100 / 57. 28.100
libavcodec     59. 37.100 / 59. 37.100
libavformat    59. 27.100 / 59. 27.100
libavdevice    59.  7.100 / 59.  7.100
libavfilter     8. 44.100 /  8. 44.100
libswscale      6.  7.100 /  6.  7.100
libswresample   4.  7.100 /  4.  7.100
libpostproc    56.  6.100 / 56.  6.100
```

FFmpeg muxer list:
```
```

**Jellyfin logs**

```
[2022-10-29 21:09:05.654 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Executing "Detect Introductions"
[2022-10-29 21:09:05.835 +02:00] [ERR] [58] ConfusedPolarBear.Plugin.IntroSkipper.Entrypoint: "The installed version of ffmpeg does not support chromaprint"
[2022-10-29 21:09:05.835 +02:00] [ERR] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error
ConfusedPolarBear.Plugin.IntroSkipper.FingerprintException: ffmpeg with chromaprint is not installed on this system - episodes will not be analyzed. If Jellyfin is running natively, install jellyfin-ffmpeg5. If Jellyfin is running in a container, upgrade it to the latest version of 10.8.0.
   at ConfusedPolarBear.Plugin.IntroSkipper.QueueManager.EnqueueAllEpisodes()
   at ConfusedPolarBear.Plugin.IntroSkipper.AnalyzeEpisodesTask.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at Emby.Server.Implementations.ScheduledTasks.ScheduledTaskWorker.ExecuteInternal(TaskOptions options)
[2022-10-29 21:09:05.835 +02:00] [INF] [58] Emby.Server.Implementations.ScheduledTasks.TaskManager: "Detect Introductions" Failed after 0 minute(s) and 0 seconds
```

**Comment by aleksasiriski** [comment]
Might I add that it worked a couple of days ago on that same image, guess an update of jellyfin or your plugin broke it?

**Comment by john-okeefe** [comment]
I'm also have this issue. I'm running arch with jellyfin and jellyfin-ffmpeg5 (built with chroma) installed from the aur. I also have ffmpeg from the arch repositories. /usr/bin/ffmpeg = arch. /usr/lib/jellyfin-ffmpeg/ffmpeg = jellyfin-ffmpeg5. Is this plugin using the jellyfin ffmpeg?

**Comment by aleksasiriski** [comment]
Sorry, got a lot on my plate currently. Stopped using the plugin for the time being. When I get more free time I'll test it again and reopen if needed.
